language: node_js
matrix:
  fast_finish: true
node_js:
- '8'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
    - pngquant
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
- travis_retry pip3.5 install --user transifex-client
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWD" >> ~/.transifexrc
script:
- yarn test
- yarn build:browser
after_success:
- (test $TRAVIS_BRANCH = "master" && test "$TRAVIS_PULL_REQUEST" = "false" && pngquant build/screenshots/* -f --ext ".png") || true
- test $TRAVIS_BRANCH = "master" && test "$TRAVIS_PULL_REQUEST" = "false" && yarn deploy:travis --branch=build
